version: '3'
services:
    frontend:
        build: ./frontend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - ./frontend:/code
        depends_on:
            - indexer
    indexer:
        build: ./indexer
        volumes:
            - ./indexer:/code
        depends_on:
            - redis
            - elasticsearch
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3.8-alpine
    redis:
        image: redis:5-alpine
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        volumes:
            - redis:/data
    elasticsearch:
        image: elasticsearch:7.6.0
        ports:
            - 4200:4200
            - 4300:4300
        environment:
            - discovery.type=single-node
        volumes:
            - esdata:/usr/share/elasticsearch/data
volumes:
    esdata:
        driver: local
    redis:
        driver: local